server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Ruta hacia el ms-usuario (Login y Registro)
        - id: ms-usuario
          uri: http://localhost:8091
          predicates:
            - Path=/api/usuarios/**

        # Ruta hacia el ms-reporte
        - id: ms-reporte
          uri: http://localhost:8092
          predicates:
            - Path=/api/reportes/**

        # Ruta hacia el ms-alerta
        - id: ms-alerta
          uri: http://localhost:8093
          predicates:
            - Path=/api/alertas/**

      # Configuración de CORS corregida
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"