server:
  port: 8092  # Cambiado de 8082 a 8092 porque el 8082 está ocupado por System

spring:
  application:
    name: ms-reporte
  datasource:
    url: jdbc:h2:mem:reportesdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect # Agregado para mejor compatibilidad
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console # Esto te permite ver la BD en http://localhost:8092/h2-console